version: "3.7"

services:
  #Nginx Service
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - php
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_HTTP_PORT}:80"
      # - "443:443"
    environment:
      - FPM_HOST=${DOCKER_PROJECT_NAME}-fpm
      - VIRTUAL_HOST=${DOCKER_HOSTNAME}
      - VIRTUAL_PORT=80
    volumes:
      - ./:/var/www:delegated
      - ./storage/app/public/:/var/www/public/storage:delegated
      - node_modules:/var/www/node_modules #effectively allows it to be ignored
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      nginx-proxy:
      default:

  #PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    hostname: ${DOCKER_PROJECT_NAME}-fpm
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - db
      - redis
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./storage/app/public/:/var/www/public/storage:delegated
      - node_modules:/var/www/node_modules #effectively allows it to be ignored
      - ./docker/php/fpm.ini:/etc/php/7.4/fpm/conf.d/fpm.ini:ro
      - ./docker/php/cli.ini:/etc/php/7.4/cli/conf.d/cli.ini:ro
      - ./docker/php/xdebug.ini:/etc/php/7.4/mods-available/xdebug.ini:ro

  #Database Service
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    hostname: ${DOCKER_PROJECT_NAME}-db}
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: ${DOCKER_PROJECT_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/:cached

  #Redis
  redis:
    image: redis:5.0.9
    restart: unless-stopped
    ports:
      - "${DOCKER_REDIS_PORT}:6379"

#Docker Networks
networks:
  default:
    driver: bridge
  nginx-proxy:
    external:
      name: nginx-proxy

#Volumes
volumes:
  node_modules:
  dbdata:
    driver: local
